package com.example.lawdcm.singleton

object DropdownDataList {
    val statesCodeList = arrayListOf(
        2, 6, 8, 27, 18, 26, 31, 32, 30, 17, 14, 5, 12, 7, 3, 4, 33, 23, 1, 25, 21, 19, 11, 22, 9,
        24, 10, 29, 20, 13, 15, 16
    )

    val statesNameList = arrayListOf(
        "Andhra Pradesh",
        "Assam",
        "Bihar",
        "Chandigarh",
        "Chhattisgarh",
        "Delhi",
        "Diu and Daman",
        "DNH at Silvassa",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jammu and Kashmir",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Ladakh",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Odisha",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal"
    )

    val caseTypeList = arrayListOf("CIVIL" , "CRIMINAL")

    val caseCategoryId = arrayListOf(
        734, 736, 853, 856, 977, 1822, 1892, 5070, 5098, 5943, 6716, 6743,
        284, 724, 1016, 1104, 1105, 1532, 1554, 1702, 1706, 1788, 1803, 1810,
        1937, 1943, 2045, 2073, 2090, 2243, 2290, 2299, 2302, 2303, 2327, 2338,
        2355, 2639, 2920, 2934, 3247, 3694, 3850, 4051, 4484, 4826, 4882, 4920,
        5003, 5032, 5085, 5188, 5539, 5559, 5671, 5707, 6049, 6748, 6769, 7014,
        7038, 7043, 7048, 7065, 7295, 7300, 7333, 7405
    )

    val caseCategoryName = arrayListOf(
        "CC - COOPERATIVE CASE",
        "GR CASE",
        "C.C. - CRIMINAL CASES",
        "S.C.C. - SUMMONS/SUMMARY CRIMINAL CASE",
        "CR. REG. CASE - CR. REGULAR",
        "NGR CASE",
        "BAIL APPLICATION",
        "C.C. - CONFISCATION CASE",
        "S.C.C. - SUMMARY CRIMINAL CASE",
        "CRIMINAL CASE",
        "ST - SUMMARY TRIAL/SESSIONS TRIAL",
        "OS - ORIGINAL SUIT",
        "ANTICIPATORY BAIL - ANTICIPATORY BAIL PETITION",
        "BAIL",
        "CHI - CHALLAN IPC",
        "CIVIL M.A.",
        "CIVIL M.J.C.",
        "COMPLAINT CASE",
        "COMPLAINT INDEX",
        "CR - CIVIL REVISION",
        "CR - CRIME CASE",
        "CR. CASE COMPLAINT (P)(CRIMINAL CASE) - CR. CASE COMPLAINT (P)",
        "CR. M. A. - CRIMINAL MISC. APPLICATION",
        "CR. MISC. CASES - CR. MISC",
        "CRI.BAIL APPLN. - BAIL APPLICATION",
        "CRI.M.A. - CRIMINAL MISC. APPLICATION",
        "CRIMINAL COMPLAINT - CR. CASE COMPLAINT (O)",
        "CRIMINAL MISC CASE (N)",
        "CRIMINAL MISC. - CRL. MISC.",
        "CRL.MISC. - CRIMINAL MISC.CASES",
        "CRLMP",
        "CRM - CRIMINAL MISC APPLICATION",
        "CRMA J",
        "CRMA S",
        "CS - CIVIL SUIT",
        "CT. CASES",
        "DOMESTIC VIOLENCE CASES",
        "EP - EXECUTION PETITION",
        "FDA - FINAL DECREE APPLICATION",
        "FINAL REPORT - FR",
        "HINDU MARRIAGE ACT",
        "MOTOR VEHICLE CLAIM ACT 1986",
        "M.V.C. - ACCIDENT CLAIM CASES U/R M.V",
        "MEX - MONEY EXECUTION",
        "MISC. CRI. APPLICATION",
        "MOTOR VEHICLE ACT",
        "NACT - 138 NIA ACT",
        "NGR CASE",
        "OMP (I) (COMM.) - COMMERCIAL ARBITRATION U/S 9",
        "OP TRAN - OP(TRANSFER)",
        "OTHER ACT",
        "P.C.R. - PRIVATE COMPLAINTS",
        "RCA CIVIL DJ ADJ - REG. CIVIL APPEAL FOR DJ ADJ",
        "RCT - RCT CASE",
        "REGULAR BAIL",
        "REMAND APPL POCSO",
        "SC.ST (PA )ACT - SC/ST (PA )ACT",
        "STC - SUMMARY TRIAL CASE",
        "SUCCESSION ACT.",
        "SUM - SUMMARY TRIAL",
        "SUMMON TRIAL",
        "SUMMONS FOR JUDGEMENT",
        "D. V. CASES - DOMESTIC VIOLENCE CASES",
        "T S ( DIV ) - T. S. ( DIV. )",
        "TRANSFER PETITION(N)",
        "TRAFFIC",
        "TRF - TRAFFIC CASES",
        "UCR - UNTRACE/CANCELLATION REPORT"
    )

    val districtCodeList = arrayListOf(
        1, 30, 13, 26, 1, 14, 5, 6, 43, 8, 1, 7, 2, 3, 15, 7, 17, 8, 18, 2, 4, 27,
        22, 24, 38, 30, 48, 17, 16, 19, 44, 2, 14, 45, 7, 27, 26, 17, 5, 12, 21, 19,
        23, 27, 67, 25, 19, 39, 18, 7, 19, 25, 36, 3, 12, 2, 29, 16, 20, 18, 15, 46,
        17, 27, 6, 1, 20, 20, 21, 28, 37, 22, 18, 34, 10, 13, 20, 21, 31, 29, 4, 33,
        50, 5, 47, 6, 2, 7, 8, 3, 1, 9, 43, 24, 18, 8, 48, 4, 10, 49, 26, 13, 3, 8,
        8, 8, 13, 27, 75, 8, 1, 13, 13, 13, 39, 20, 41, 29, 17, 25, 13, 5, 3, 30, 6,
        33, 18, 6, 20, 1, 22, 24, 17, 2, 27, 17, 17, 17, 8, 13, 3, 14, 5, 30, 16, 41,
        40, 40, 11, 5, 9, 38, 1, 9, 17, 7, 34, 16, 2, 7, 28, 27, 6, 1, 15, 2, 24, 7,
        3, 4, 4, 1, 11, 2, 24, 25, 33, 49, 5, 9, 63, 15, 4, 9, 26, 6, 29, 8, 12, 9, 7,
        11, 7, 4, 4, 20, 20, 35, 8, 28, 37, 10, 18, 6, 19, 6, 50, 11, 23, 3, 5, 30, 5,
        10, 6, 44, 3, 21, 1, 64, 11, 73, 4, 4, 9, 23, 65, 11, 7, 7, 2, 3, 18, 11, 2, 7,
        1, 2, 47, 1, 14, 38, 4, 4, 40, 32, 19, 2, 70, 3, 18, 21, 4, 19, 23, 12, 15, 18,
        16, 12, 36, 9, 8, 22, 66, 25, 12, 18, 9, 39, 28, 11, 24, 35, 26, 7, 2, 16, 4, 10,
        23, 23, 1, 31, 23, 2, 13, 69, 7, 3, 51, 19, 40, 11, 29, 26, 17, 12, 3, 1, 19, 1,
        1, 5, 34, 37, 9, 2, 13, 14, 4, 10, 25, 10, 24, 8, 9, 25, 22, 25, 3, 22, 19, 34,
        15, 22, 7, 6, 1, 11, 20, 10, 5, 11, 26, 20, 10, 11, 10, 10, 34, 5, 10, 19, 13, 23,
        19, 28, 16, 8, 24, 1, 2, 12, 18, 15, 41, 5, 52, 40, 42, 43, 12, 15, 42, 38, 14, 11,
        1, 31, 6, 41, 16, 35, 22, 2, 13, 53, 42, 26, 6, 6, 8, 68, 12, 24, 54, 39, 15, 4, 10,
        37, 23, 39, 38, 24, 11, 12, 26, 38, 26, 32, 22, 10, 6, 9, 1, 30, 15, 7, 5, 1, 15, 1,
        33, 11, 2, 20, 32, 27, 22, 17, 15, 7, 8, 4, 14, 21, 1, 1, 2, 5, 3, 19, 29, 14, 8,
        19, 23, 14, 27, 18, 7, 17, 24, 7, 28, 12, 21, 5, 1, 2, 23, 13, 15, 12, 36, 17, 23,
        31, 28, 2, 6, 25, 18, 9, 15, 9, 10, 55, 6, 24, 6, 3, 24, 14, 16, 10, 13, 1, 28, 21,
        14, 23, 56, 22, 9, 42, 32, 21, 9, 46, 17, 5, 12, 13, 16, 3, 29, 43, 57, 21, 21, 12,
        3, 21, 11, 74, 35, 19, 71, 4, 31, 32, 36, 15, 25, 5, 33, 9, 15, 2, 11, 58, 19, 76,
        20, 37, 12, 11, 15, 23, 10, 11, 59, 21, 35, 1, 18, 33, 31, 3, 26, 2, 31, 16, 29, 3,
        29, 5, 30, 60, 13, 20, 6, 10, 13, 11, 2, 20, 6, 3, 14, 19, 5, 61, 16, 22, 21, 14,
        30, 4, 9, 34, 23, 3, 21, 17, 16, 4, 9, 9, 4, 4, 36, 2, 8, 3, 33, 32, 22, 25, 5, 18,
        9, 24, 4, 2, 16, 45, 5, 4, 5, 62, 10, 6, 31, 39, 35, 27, 11, 28, 3, 10, 14, 20, 21,
        10, 8, 36, 16, 9, 2, 23, 3, 7, 4, 1, 30, 20, 14
    )

    val districtList = arrayListOf(
        "Adilabad", "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Akola", "Alappuzha",
        "Aligarh", "Alirajpur", "Allahabad", "Almora", "Alwar", "Ambala", "Ambedkar Nagar",
        "Amravati", "Amreli", "Amritsar", "Anand", "Ananthapur", "Anantnag", "Anugul", "Anuppur",
        "Araria", "Aravalli at Modasa", "Ariyalur", "Ashoknagar", "Auraiya", "Aaurangabad",
        "Aurangabad", "Azamgarh", "BAGALKOT", "Bageshwar", "Baghpat", "Bahraich", "Baksa", "Balaghat",
        "Balangir", "Balasore", "BALLARI", "Ballia", "Balod", "Balodabazar", "Balotra Barmer",
        "Balrampur", "Balrampur Ramanujganj", "Banaskanth at Palanpur", "Banda", "Bandipora", "Banka",
        "Bankura", "Banswara", "Barabanki", "Baramulla", "Baran", "Bareilly", "Bargarh", "Barnala",
        "Barpeta", "Barwani", "Bastar", "Basti", "Bathinda", "Beed", "Begusarai", "BELAGAVI", "Bemetara",
        "BENGALURU", "BENGALURU RURAL", "Bettiah", "Betul", "Bhadohi SR Nagar", "Bhadrak", "Bhagalpur",
        "Bhandara", "Bharatpur", "Bharuch", "Bhavnagar", "Bhilwara", "Bhind", "Bhiwani", "Bhojpur",
        "Bhopal", "BIDAR", "Bijnor", "Bikaner", "Bilaaspur", "Bilaspur", "Birbhum", "Bishnupur", "Bokaro",
        "Bongaigaon", "BOTAD", "Boudh", "Budaun", "Budgam", "Bulandshahr", "Buldhana", "Bundi", "Burhanpur",
        "Buxar", "Cachar", "Calcutta", "Central", "Chamba", "Chamoli", "Champawat", "CHAMRAJNAGAR",
        "Chandauli", "Chandel", "Chandigarh", "Chandrapur", "Chatra", "Chennai", "Chhatarpur", "Chhindwara",
        "Chhota Udepur", "CHIKKABALLAPUR", "CHIKKAMAGALURU", "Chirang", "CHITRADURGA", "Chitrakoot",
        "Chittoor", "Chittorgarh", "Churachandpur", "Churu", "Coimbatore", "Coochbehar", "Cuddalore",
        "Cuttack", "Dahod", "DAKSHINA KANNADA", "Daltonganj", "Daman", "Damoh", "Dantewada", "Darbhanga",
        "Darjeeling", "Darrang", "Datia", "Dausa", "DAVANGERE", "Dehradun", "Deogarh", "Deoghar", "Deoria",
        "Devbhumi Dwarka at Khambhaliya", "Dewas", "Dhalai Tripura", "Dhamtari", "Dhanbad", "Dhar",
        "Dharmapuri", "DHARWAD", "Dhemaji", "Dhenkanal", "Dholpur", "Dhubri", "Dhule", "Dibrugarh",
        "Dima Hasao",
        "Dindigul",
        "Dindori",
        "Diu",
        "Doda",
        "Dumka",
        "Dungarpur",
        "Durg",
        "East",
        "East Garo Hills",
        "East Godavari",
        "East Khasi Hills",
        "East Singhbhum at Jamshedpur",
        "Ernakulam",
        "Erode",
        "Etah",
        "Etawah",
        "Faizabad",
        "Faridabad",
        "Faridkot",
        "Farrukhabad",
        "Fatehabad",
        "Fatehgarh Sahib",
        "Fatehpur",
        "Fazilka",
        "Ferozepur",
        "Firozabad",
        "GADAG",
        "Gadchiroli",
        "Gajapati",
        "Ganderbal",
        "GANDHINAGAR",
        "Ganganagar",
        "Gangtok",
        "Ganjam",
        "Garhwa",
        "Gautam Buddha Nagar",
        "Gaya",
        "Ghaziabad",
        "Ghazipur",
        "Gir Somnath at Veraval",
        "Giridih",
        "Goalpara",
        "Godda",
        "Golaghat",
        "Gomati District",
        "Gonda",
        "Gondia",
        "Gopalganj",
        "Gorakhpur",
        "Gumla",
        "Guna",
        "Guntur",
        "Gurdaspur",
        "Gurugram",
        "Gwalior",
        "Gyalshing",
        "Hailakandi",
        "Hamirpur",
        "Hamirpurr",
        "Hanumangarh",
        "Hapur",
        "Harda",
        "Hardoi",
        "Haridwar",
        "HASSAN",
        "Hathras",
        "HAVERI",
        "Hazaribagh",
        "Hisar",
        "Hooghly",
        "Hoshangabad",
        "Hoshiarpur",
        "Howrah",
        "Hyderabad",
        "Idukki",
        "Imphal East",
        "Imphal West",
        "Indore",
        "Jabalpur",
        "Jagatsinghpur",
        "Jaipur District",
        "Jaipur Metro",
        "Jaipur Metro I",
        "Jaipur Metro II",
        "Jaiselmer",
        "Jajpur",
        "Jalandhar",
        "Jalaun",
        "Jalgaon",
        "Jalna",
        "Jalore",
        "Jalpaiguri",
        "Jammu",
        "Jamnagar",
        "Jamtara",
        "Jamui",
        "Janjgir",
        "Jashpur",
        "Jaunpur",
        "Jehanabad",
        "Jhabua",
        "Jhajjar",
        "Jhalawar",
        "Jhansi",
        "Jhargram",
        "Jharsuguda",
        "Jhunjhunu",
        "Jind",
        "Jodhpur District",
        "Jodhpur Metro",
        "Jorhat",
        "Junagadh",
        "Jyotiba Phule Nagar",
        "kachchh at Bhuj",
        "Kadapa",
        "Kaimur at Bhabhua",
        "Kaithal",
        "KALABURAGI",
        "Kalahandi",
        "kalimpong",
        "Kamrup",
        "Kamrup Metro",
        "Kancheepuram",
        "Kandhamal",
        "Kangra",
        "Kanker",
        "Kannauj",
        "Kanniyakumari",
        "Kannur",
        "Kanpur Dehat",
        "Kanpur Nagar",
        "Kanshi Ram Nagar",
        "Kapurthala",
        "Karauli",
        "Karbi Anglong",
        "Kargil",
        "Karimganj",
        "Karimnagar",
        "Karnal",
        "Karur",
        "Kasaragod",
        "Kathua",
        "Katihar",
        "Katni",
        "Kaushambi",
        "Kawardha",
        "Kendrapada",
        "Keonjhar",
        "Khagaria",
        "Khammam",
        "Khandwa",
        "Kheda at Nadiad",
        "Khowai Tripura",
        "KHUNTI",
        "Khurda",
        "Kinnaur",
        "Kishanganj",
        "Kishtwar",
        "KODAGU",
        "Koderma",
        "Kokrajhar",
        "KOLAR",
        "Kolhapur",
        "Kollam",
        "Kondagaon",
        "KOPPAL",
        "Koraput",
        "Korba",
        "Koriya",
        "Kota",
        "Kottayam",
        "Kozhikode",
        "Krishna",
        "Krishnagiri",
        "Kulgam",
        "Kullu",
        "Kupwara",
        "Kurnool",
        "Kurukshetra",
        "Kushinagar",
        "Lakhimpur",
        "Lakhimpura",
        "Lakhisarai",
        "Lakshadweep",
        "Lalitpur",
        "Latehar",
        "Latur",
        "Leh",
        "Lohardaga",
        "Lucknow",
        "Ludhiana",
        "Lunglei",
        "Madhepura",
        "Madhubani",
        "Madurai",
        "Mah State Cooperative Appellat",
        "Mahabubnagar",
        "Maharajganj",
        "Maharashtra Industrial and Lab",
        "Maharashtra-Family Courts",
        "Maharashtra-School Tribunals",
        "Mahasamund",
        "Mahesana",
        "Mahisagar at Lunawada",
        "Mahoba",
        "Mainpuri",
        "Malappuram",
        "Malda",
        "Malkangiri",
        "Mandi",
        "Mandla",
        "Mandleshwar",
        "Mandsaur",
        "MANDYA",
        "Mangan",
        "Mansa",
        "Mathura",
        "Mau",
        "Mayurbhanj",
        "Medak",
        "Meerut",
        "Merta (Nagaur)",
        "Mirzapur",
        "Moga",
        "Mohali",
        "Moradabad",
        "MORBI",
        "Morena",
        "Morigaon",
        "Motihari",
        "Mumbai City Civil Court",
        "Mumbai CMM Courts",
        "Mumbai Motor Accident Claims T",
        "Mumbai Small Causes Court",
        "Mungeli",
        "Munger",
        "Murshidabad",
        "Muzaffarnagar",
        "Muzaffarpur",
        "MYSURU",
        "Nabarangpur",
        "Nadia",
        "Nagaon",
        "Nagapattinam",
        "Nagpur",
        "Nainital",
        "Nalanda",
        "Nalbari",
        "Nalgonda",
        "Namakkal",
        "Namchi",
        "Nanded",
        "Nandurbar",
        "Narmada",
        "Narnaul",
        "Narsinghpur",
        "Nashik",
        "Navsari",
        "Nawada",
        "Nayagarh",
        "Neemuch",
        "Nellore",
        "New Delhi",
        "Nizamabad",
        "North",
        "North Twenty Four Parganas",
        "North Dinajpur",
        "North East",
        "North Goa",
        "North Tripura",
        "North West",
        "Nuapada",
        "Nuh",
        "Osmanabad",
        "Pakur",
        "Palakkad",
        "Pali",
        "Palwal",
        "Panchkula",
        "Panchmahal at Godhra",
        "Panipat",
        "Panna",
        "Parbhani",
        "Paschim Bardhaman",
        "Paschim Medinpur",
        "Patan",
        "Pathanamthitta",
        "Pathankot",
        "Patiala",
        "Patna",
        "Pauri Garhwal",
        "Perambalur",
        "Pilibhit",
        "Pithoragarh",
        "Poonch",
        "Porbandar",
        "Prakasham",
        "Partapgarh",
        "Pratapgarh",
        "Puducherry",
        "Pudukkottai",
        "Pulwama",
        "Pune",
        "Purba Bardhaman",
        "Purba Medinipur",
        "Puri",
        "Purnea",
        "Purulia",
        "Raebareli",
        "RAICHUR",
        "Raigad",
        "Raigarh",
        "Raipur",
        "Raisen",
        "Rajgarh",
        "RAJKOT",
        "Rajnandgaon",
        "Rajouri",
        "Rajsamand",
        "RAMANAGARAM",
        "Ramanathapuram",
        "Ramban",
        "RAMGARH",
        "Rampur",
        "Ranchi",
        "Rangareddy",
        "Ratlam",
        "Ratnagiri",
        "Rayagada",
        "Reasi",
        "Rewa",
        "Rewari",
        "Ri Bhoi",
        "Rohtak",
        "Rohtas Sasaram",
        "Rudraprayag",
        "Rupnagar",
        "Sabarkantha at Himmatnagar",
        "Sagar",
        "Saharanpur",
        "Saharsa",
        "Sahibganj",
        "Salem",
        "Samastipur",
        "Samba",
        "Sambalpur",
        "Sambhal at Chandausi",
        "Sangli",
        "Sangrur",
        "Santkabir Nagar",
        "Saran at Chapra",
        "Satara",
        "Satna",
        "Sawai Madhopur",
        "SBS Nagar",
        "Sehore",
        "Senapati",
        "Seoni",
        "Sepahijala Tripura",
        "Seraikella",
        "Shahdara",
        "Shahdol",
        "Shahjahanpur",
        "Shajapur",
        "Shamli",
        "Sheikhpura",
        "Sheohar",
        "Sheopur",
        "Shimla",
        "SHIVAMOGGA",
        "Shivpuri",
        "Shopian",
        "Shravasti",
        "Siddharthnagar",
        "Sidhi",
        "Sikar",
        "Silvassa",
        "Simdega",
        "Sindhudurg",
        "Singrauli",
        "Sirmaur",
        "Sirohi",
        "Sirsa",
        "Sitamarhi",
        "Sitapur",
        "Sivagangai",
        "Sivasagar",
        "Siwan",
        "Solan",
        "Solapur",
        "Sonbhadra",
        "Sonepat",
        "Sonepur",
        "Sonitpur",
        "South",
        "South Dinajpur",
        "South East",
        "South Goa",
        "South Twenty Four Parganas",
        "South West",
        "SouthTripura",
        "Sri Muktsar Sahib",
        "Srikakulam",
        "Srinagar",
        "Sultanpur",
        "Sundargarh",
        "Supaul",
        "Surajpur",
        "SURAT",
        "Surendranagar",
        "Surguja",
        "Tamenglong",
        "Tapi",
        "Tarn Taran",
        "Tehri Garhwal",
        "Thane",
        "Thanjavur",
        "The Nilgiris",
        "Theni",
        "Thiruvananthapuram",
        "Thoothukudi",
        "Thoubal",
        "Thrissur",
        "Tikamgarh",
        "Tinsukia",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tiruppur",
        "Tiruvallur",
        "Tiruvannamalai",
        "Tiruvarur",
        "Tonk",
        "TUMAKURU",
        "Udaipur",
        "Udalguri",
        "Udham Singh Nagar",
        "Udhampur",
        "UDUPI",
        "Ujjain",
        "Umaria",
        "Una",
        "Unakoti Tripura",
        "Unnao",
        "UTTARA KANNADA",
        "Uttarkashi",
        "Vadodara",
        "Vaishali",
        "Valsad",
        "Varanasi",
        "Vellore",
        "Vidisha",
        "VIJAYAPURA",
        "Viluppuram",
        "Virudhunagar",
        "Visakapatnam",
        "Vizianagaram",
        "Warangal",
        "Wardha",
        "Washim",
        "Wayanad",
        "West",
        "West Garo Hills",
        "West Godavari",
        "West Jaintia Hills",
        "West Khasi Hills",
        "West Singhbhum at Chaibasa",
        "West Tripura",
        "YADGIR.",
        "Yamunanagar",
        "Yavatmal"
    )

    val districtsAndhraPradesh = arrayListOf(
        "district_name",
        "Ananthapur",
        "Chittoor",
        "East Godavari",
        "Guntur",
        "Kadapa",
        "Krishna",
        "Kurnool",
        "Nellore",
        "Prakasham",
        "Srikakulam",
        "Visakapatnam",
        "Vizianagaram",
        "West Godavari"
    )

    val districtsAssam = arrayListOf(
        "Baksa",
        "Barpeta",
        "Bongaigaon",
        "Cachar",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dhubri",
        "Dibrugarh",
        "Dima Hasao",
        "Goalpara",
        "Golaghat",
        "Hailakandi",
        "Jorhat",
        "Kamrup",
        "Kamrup Metro",
        "Karbi Anglong",
        "Karimganj",
        "Kokrajhar",
        "Lakhimpur",
        "Morigaon",
        "Nagaon",
        "Nalbari",
        "Sivasagar",
        "Sonitpur",
        "Tinsukia",
        "Udalguri"
    )

    val districtsBihar = arrayListOf(
        "Araria",
        "Aaurangabad",
        "Banka",
        "Begusarai",
        "Bettiah",
        "Bhagalpur",
        "Bhojpur",
        "Buxar",
        "Darbhanga",
        "Gaya",
        "Gopalganj",
        "Jamui",
        "Jehanabad",
        "Kaimur at Bhabhua",
        "Katihar",
        "Khagaria",
        "Kishanganj",
        "Lakhisarai",
        "Madhepura",
        "Madhubani",
        "Motihari",
        "Munger",
        "Muzaffarpur",
        "Nalanda",
        "Nawada",
        "Patna",
        "Purnea",
        "Rohtas Sasaram",
        "Saharsa",
        "Samastipur",
        "Saran at Chapra",
        "Sheikhpura",
        "Sheohar",
        "Sitamarhi",
        "Siwan",
        "Supaul",
        "Vaishali"
    )

    val districtsChandigarh = arrayListOf("Chandigarh")

    val districtsChattisgarh = arrayListOf(
        "Balod",
        "Balodabazar",
        "Balrampur Ramanujganj",
        "Bastar",
        "Bemetara",
        "Bilaaspur",
        "Dantewada",
        "Dhamtari",
        "Durg",
        "Janjgir",
        "Jashpur",
        "Kanker",
        "Kawardha",
        "Kondagaon",
        "Korba",
        "Koriya",
        "Mahasamund",
        "Mungeli",
        "Raigarh",
        "Raipur",
        "Rajnandgaon",
        "Surajpur",
        "Surguja"
    )

    val districtsDelhi = arrayListOf(
        "Central",
        "East",
        "New Delhi",
        "North",
        "North East",
        "North West",
        "Shahdara",
        "South",
        "South East",
        "South West",
        "West"
    )

    val districtsDiuDaman = arrayListOf("Daman", "Diu")

    val districtsDNHatSilvasa = arrayListOf("Silvassa")

    val districtsGoa = listOf("North Goa", "South Goa")

    val districtsGujarat = arrayListOf(
        "Ahmedabad",
        "Amreli",
        "Anand",
        "Aravalli at Modasa",
        "Banaskanth at Palanpur",
        "Bharuch",
        "Bhavnagar",
        "BOTAD",
        "Chhota Udepur",
        "Dahod",
        "Devbhumi Dwarka at Khambhaliya",
        "GANDHINAGAR",
        "Gir Somnath at Veraval",
        "Jamnagar",
        "Junagadh",
        "kachchh at Bhuj",
        "Kheda at Nadiad",
        "Mahesana",
        "Mahisagar at Lunawada",
        "MORBI",
        "Narmada",
        "Navsari",
        "Panchmahal at Godhra",
        "Patan",
        "Porbandar",
        "RAJKOT",
        "Sabarkantha at Himmatnagar",
        "SURAT",
        "Surendranagar",
        "Tapi",
        "Vadodara",
        "Valsad"
    )

    val districtsHaryana = arrayListOf(
        "Ambala",
        "Bhiwani",
        "Faridabad",
        "Fatehabad",
        "Gurugram",
        "Hisar",
        "Jhajjar",
        "Jind",
        "Kaithal",
        "Karnal",
        "Kurukshetra",
        "Narnaul",
        "Nuh",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Rewari",
        "Rohtak",
        "Sirsa",
        "Sonepat",
        "Yamunanagar"
    )

    val districtsHimachalPradesh = arrayListOf(
        "Bilaspur",
        "Chamba",
        "Hamirpur",
        "Kangra",
        "Kinnaur",
        "Kullu",
        "Mandi",
        "Shimla",
        "Sirmaur",
        "Solan",
        "Una"
    )

    val districtsJammuKashmir = arrayListOf(
        "Anantnag",
        "Bandipora",
        "Baramulla",
        "Budgam",
        "Doda",
        "Ganderbal",
        "Jammu",
        "Kargil",
        "Kathua",
        "Kishtwar",
        "Kulgam",
        "Kupwara",
        "Leh",
        "Poonch",
        "Pulwama",
        "Rajouri",
        "Ramban",
        "Reasi",
        "Samba",
        "Shopian",
        "Srinagar",
        "Udhampur"
    )

    val districtsJharkhand = arrayListOf(
        "Bokaro",
        "Chatra",
        "Daltonganj",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "East Singhbhum at Jamshedpur",
        "Garhwa",
        "Giridih",
        "Godda",
        "Gumla",
        "Hazaribagh",
        "Jamtara",
        "KHUNTI",
        "Koderma",
        "Latehar",
        "Lohardaga",
        "Pakur",
        "RAMGARH",
        "Ranchi",
        "Sahibganj",
        "Seraikella",
        "Simdega",
        "West Singhbhum at Chaibasa"
    )

    val districtsKarnataka = arrayListOf(
        "BAGALKOT",
        "BALLARI",
        "BELAGAVI",
        "BENGALURU",
        "BENGALURU RURAL",
        "BIDAR",
        "CHAMRAJNAGAR",
        "CHIKKABALLAPUR",
        "CHIKKAMAGALURU",
        "CHITRADURGA",
        "DAKSHINA KANNADA",
        "DAVANGERE",
        "DHARWAD",
        "GADAG",
        "HASSAN",
        "HAVERI",
        "KALABURAGI",
        "KODAGU",
        "KOLAR",
        "KOPPAL",
        "MANDYA",
        "MYSURU",
        "RAICHUR",
        "RAMANAGARAM",
        "SHIVAMOGGA",
        "TUMAKURU",
        "UDUPI",
        "UTTARA KANNADA",
        "VIJAYAPURA",
        "YADGIR"
    )

    val districtsKerala = arrayListOf(
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Lakshadweep",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thiruvananthapuram",
        "Thrissur",
        "Wayanad"
    )

    val districtsMadhyaPradesh = arrayListOf(
        "Alirajpur",
        "Anuppur",
        "Ashoknagar",
        "Balaghat",
        "Barwani",
        "Betul",
        "Bhind",
        "Bhopal",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Damoh",
        "Datia",
        "Dewas",
        "Dhar",
        "Dindori",
        "Guna",
        "Gwalior",
        "Harda",
        "Hoshangabad",
        "Indore",
        "Jabalpur",
        "Jhabua",
        "Katni",
        "Khandwa",
        "Mandla",
        "Mandleshwar",
        "Mandsaur",
        "Morena",
        "Narsinghpur",
        "Neemuch",
        "Panna",
        "Raisen",
        "Rajgarh",
        "Ratlam",
        "Rewa",
        "Sagar",
        "Satna",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Sidhi",
        "Singrauli",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha"
    )

    val districtsMaharashtra = arrayListOf(
        "Ahmednagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Beed",
        "Bhandara",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Jalgaon",
        "Jalna",
        "Kolhapur",
        "Latur",
        "Mah State Cooperative Appellat",
        "Maharashtra Industrial and Lab",
        "Maharashtra-Family Courts",
        "Maharashtra-School Tribunals",
        "Mumbai City Civil Court",
        "Mumbai CMM Courts",
        "Mumbai Motor Accident Claims T",
        "Mumbai Small Causes Court",
        "Nagpur",
        "Nanded",
        "Nandurbar",
        "Nashik",
        "Osmanabad",
        "Parbhani",
        "Pune",
        "Raigad",
        "Ratnagiri",
        "Sangli",
        "Satara",
        "Sindhudurg",
        "Solapur",
        "Thane",
        "Wardha",
        "Washim",
        "Yavatmal"
    )

    val districtsManipur = arrayListOf(
        "Bishnupur",
        "Chandel",
        "Churachandpur",
        "Imphal East",
        "Imphal West",
        "Senapati",
        "Tamenglong",
        "Thoubal"
    )

    val districtsMeghalaya = arrayListOf(
        "East Garo Hills",
        "East Khasi Hills",
        "Ri Bhoi",
        "West Garo Hills",
        "West Jaintia Hills",
        "West Khasi Hills"
    )

    val districtsMizoram = arrayListOf(
        "Aizawl",
        "Lunglei"
    )

    val districtsOdisha = arrayListOf(
        "Anugul",
        "Balangir",
        "Balasore",
        "Bargarh",
        "Bhadrak",
        "Boudh",
        "Cuttack",
        "Deogarh",
        "Dhenkanal",
        "Gajapati",
        "Ganjam",
        "Jagatsinghpur",
        "Jajpur",
        "Jharsuguda",
        "Kalahandi",
        "Kandhamal",
        "Kendrapada",
        "Keonjhar",
        "Khurda",
        "Koraput",
        "Malkangiri",
        "Mayurbhanj",
        "Nabarangpur",
        "Nayagarh",
        "Nuapada",
        "Puri",
        "Rayagada",
        "Sambalpur",
        "Sonepur",
        "Sundargarh"
    )

    val districtsPunjab = arrayListOf(
        "Amritsar",
        "Barnala",
        "Bathinda",
        "Faridkot",
        "Fatehgarh Sahib",
        "Fazilka",
        "Ferozepur",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Kapurthala",
        "Ludhiana",
        "Mansa",
        "Moga",
        "Mohali",
        "Pathankot",
        "Patiala",
        "Rupnagar",
        "Sangrur",
        "SBS Nagar",
        "Sri Muktsar Sahib",
        "Tarn Taran"
    )

    val districtsRajasthan = arrayListOf(
        "Ajmer",
        "Alwar",
        "Balotra Barmer",
        "Banswara",
        "Baran",
        "Bharatpur",
        "Bhilwara",
        "Bikaner",
        "Bundi",
        "Chittorgarh",
        "Churu",
        "Dausa",
        "Dholpur",
        "Dungarpur",
        "Ganganagar",
        "Hanumangarh",
        "Jaipur District",
        "Jaipur Metro",
        "Jaipur Metro I",
        "Jaipur Metro II",
        "Jaiselmer",
        "Jalore",
        "Jhalawar",
        "Jhunjhunu",
        "Jodhpur District",
        "Jodhpur Metro",
        "Karauli",
        "Kota",
        "Merta (Nagaur)",
        "Pali",
        "Partapgarh",
        "Rajsamand",
        "Sawai Madhopur",
        "Sikar",
        "Sirohi",
        "Tonk",
        "Udaipur"
    )

    val districtsSikkim = arrayListOf(
        "Gangtok",
        "Gyalshing",
        "Mangan",
        "Namchi"
    )

    val districtsTamilNaduAndPuducherry = arrayListOf(
        "Ariyalur",
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kancheepuram",
        "Kanniyakumari",
        "Karur",
        "Krishnagiri",
        "Madurai",
        "Nagapattinam",
        "Namakkal",
        "Perambalur",
        "Puducherry",
        "Pudukkottai",
        "Ramanathapuram",
        "Salem",
        "Sivagangai",
        "Thanjavur",
        "The Nilgiris",
        "Theni",
        "Thoothukudi",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tiruppur",
        "Tiruvallur",
        "Tiruvannamalai",
        "Tiruvarur",
        "Vellore",
        "Viluppuram",
        "Virudhunagar"
    )

    val districtsTelangana = arrayListOf(
        "Adilabad",
        "Hyderabad",
        "Karimnagar",
        "Khammam",
        "Mahabubnagar",
        "Medak",
        "Nalgonda",
        "Nizamabad",
        "Rangareddy",
        "Warangal"
    )

    val districtsTripura = arrayListOf(
        "Dhalai Tripura",
        "Gomati District",
        "Khowai Tripura",
        "North Tripura",
        "Sepahijala Tripura",
        "SouthTripura",
        "Unakoti  Tripura",
        "West Tripura"
    )

    val districtsUttarPradesh = arrayListOf(
        "Agra",
        "Aligarh",
        "Allahabad",
        "Ambedkar Nagar",
        "Auraiya",
        "Azamgarh",
        "Baghpat",
        "Bahraich",
        "Ballia",
        "Balrampur",
        "Banda",
        "Barabanki",
        "Bareilly",
        "Basti",
        "Bhadohi SR Nagar",
        "Bijnor",
        "Budaun",
        "Bulandshahr",
        "Chandauli",
        "Chitrakoot",
        "Deoria",
        "Etah",
        "Etawah",
        "Faizabad",
        "Farrukhabad",
        "Fatehpur",
        "Firozabad",
        "Gautam Buddha Nagar",
        "Ghaziabad",
        "Ghazipur",
        "Gonda",
        "Gorakhpur",
        "Hamirpurr",
        "Hapur",
        "Hardoi",
        "Hathras",
        "Jalaun",
        "Jaunpur",
        "Jhansi",
        "Jyotiba Phule Nagar",
        "Kannauj",
        "Kanpur Dehat",
        "Kanpur Nagar",
        "Kanshi Ram Nagar",
        "Kaushambi",
        "Kushinagar",
        "Lakhimpura",
        "Lalitpur",
        "Lucknow",
        "Maharajganj",
        "Mahoba",
        "Mainpuri",
        "Mathura",
        "Mau",
        "Meerut",
        "Mirzapur",
        "Moradabad",
        "Muzaffarnagar",
        "Pilibhit",
        "Pratapgarh",
        "Raebareli",
        "Rampur",
        "Saharanpur",
        "Sambhal at Chandausi",
        "Santkabir Nagar",
        "Shahjahanpur",
        "Shamli",
        "Shravasti",
        "Siddharthnagar",
        "Sitapur",
        "Sonbhadra",
        "Sultanpur",
        "Unnao",
        "Varanasi"
    )

    val districtsUttarakhand = arrayListOf(
        "Almora",
        "Bageshwar",
        "Chamoli",
        "Champawat",
        "Dehradun",
        "Haridwar",
        "Nainital",
        "Pauri Garhwal",
        "Pithoragarh",
        "Rudraprayag",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Uttarkashi"
    )

    val districtsWestBengal = arrayListOf(
        "Bankura",
        "Birbhum",
        "Calcutta",
        "Coochbehar",
        "Darjeeling",
        "Hooghly",
        "Howrah",
        "Jalpaiguri",
        "Jhargram",
        "kalimpong",
        "Malda",
        "Murshidabad",
        "Nadia",
        "North  Twenty Four Parganas",
        "North Dinajpur",
        "Paschim Bardhaman",
        "Paschim Medinpur",
        "Purba Bardhaman",
        "Purba Medinipur",
        "Purulia",
        "South Dinajpur",
        "South Twenty Four Parganas"
    )

    val caseCategoryHashMap : HashMap<String , Int> = hashMapOf()
    val caseStateHashMap : HashMap<String , Int> = hashMapOf()
    init {
        caseCategoryId.forEachIndexed { index, s ->
            caseCategoryHashMap.put(caseCategoryName[index] , s)
        }

        statesCodeList.forEachIndexed { index, s ->
            caseStateHashMap.put(statesNameList[index] , s)
        }
    }
}